steps:
# Build and tag using commit sha
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-t', 'europe-west1-docker.pkg.dev/healthhero-366717/apps/gke-cluster-info:${COMMIT_SHA}', '-f', 'Dockerfile']
# Push the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/healthhero-366717/apps/gke-cluster-info:${COMMIT_SHA}']
# Create release in Google Cloud Deploy
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      "deploy", "releases", "create", "rel-${SHORT_SHA}",
      "--delivery-pipeline", "gke-cluster-info",
      "--region", "europe-west1",
      "--images", "IMAGE_NAME=europe-west1-docker.pkg.dev/healthhero-366717/apps/gke-cluster-info:${COMMIT_SHA}"
    ]
