apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: gke-cluster-info
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: gke-cluster-info
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50
