apiVersion: v1
kind: Service
metadata:
  name: gke-cluster-info
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: gke-cluster-info
  type: LoadBalancer